spring.application.name=productService

# Server config
server.port=8081

# Database connection
spring.datasource.url=${DB_URL_LOCAL}
spring.datasource.username=${DB_USERNAME_LOCAL}
spring.datasource.password=${DB_PASSWORD_LOCAL}

# 1. DATABASE & FLYWAY
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

# 2. NAMNGIVNING (Mappar 'imageUrl' i Java till 'image_url' i DB)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# 3. LOGGNING & DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jpa=INFO